#!/usr/bin/env bash
# docs-hub-sync — Symlink project docs into the Obsidian docs-hub vault
# Part of the docs-hub plugin (m86-claude-marketplace)

set -euo pipefail

VAULT_DIR="$HOME/Ops/docs-hub"
SCAN_ROOTS=("$HOME/One" "$HOME/Workbench" "$HOME/Lab")
INDEX_FILE="$VAULT_DIR/_index.md"
MAX_DEPTH=2

# Ensure vault exists
if [[ ! -d "$VAULT_DIR" ]]; then
  echo "docs-hub-sync: vault not found at $VAULT_DIR — run /docs-hub-setup first"
  exit 1
fi

# Track what we linked for the index
declare -a PROJECTS=()

echo "docs-hub-sync: scanning for docs directories..."

# --- Create symlinks ---
for root in "${SCAN_ROOTS[@]}"; do
  [[ -d "$root" ]] || continue
  root_name=$(basename "$root")

  while IFS= read -r docs_dir; do
    project_dir=$(dirname "$docs_dir")
    project_name=$(basename "$project_dir")

    # Skip worktrees, node_modules, .claude
    [[ "$docs_dir" == *".worktrees"* ]] && continue
    [[ "$docs_dir" == *"node_modules"* ]] && continue
    [[ "$docs_dir" == *".claude"* ]] && continue

    if [[ "$project_dir" == "$root" ]]; then
      link_name="$root_name"
    else
      link_name="$root_name/$project_name"
    fi

    link_path="$VAULT_DIR/$link_name"
    mkdir -p "$(dirname "$link_path")"

    if [[ -L "$link_path" ]]; then
      current_target=$(readlink "$link_path")
      if [[ "$current_target" != "$docs_dir" ]]; then
        rm "$link_path"
        ln -s "$docs_dir" "$link_path"
        echo "  updated: $link_name → $docs_dir"
      fi
    elif [[ -e "$link_path" ]]; then
      echo "  SKIP: $link_path exists and is not a symlink"
    else
      ln -s "$docs_dir" "$link_path"
      echo "  linked: $link_name → $docs_dir"
    fi

    doc_count=$(find -L "$docs_dir" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
    PROJECTS+=("$link_name|$doc_count|$docs_dir")

  done < <(find "$root" -maxdepth "$MAX_DEPTH" -type d -name "docs" 2>/dev/null | sort)
done

# --- Prune stale symlinks ---
find "$VAULT_DIR" -type l ! -exec test -e {} \; -print | while read -r stale; do
  echo "  pruned: $stale"
  rm "$stale"
done
find "$VAULT_DIR" -mindepth 1 -type d -empty -not -path "*/.obsidian/*" -delete 2>/dev/null || true

# --- Generate index ---
cat > "$INDEX_FILE" << 'HEADER'
---
title: Docs Hub
description: Auto-generated index of all project documentation
updated: TIMESTAMP
---

# Docs Hub

> Auto-generated by `docs-hub-sync.sh`. Do not edit manually.

HEADER

sed -i '' "s/TIMESTAMP/$(date -Iseconds)/" "$INDEX_FILE"

current_root=""
for entry in $(printf '%s\n' "${PROJECTS[@]}" | sort); do
  IFS='|' read -r link_name doc_count source_path <<< "$entry"
  entry_root=$(dirname "$link_name")

  if [[ "$entry_root" == "." ]]; then
    entry_root="$link_name"
  fi

  if [[ "$entry_root" != "$current_root" ]]; then
    case "$entry_root" in
      One)       desc="Core platform" ;;
      Workbench) desc="Active projects" ;;
      Lab)       desc="Experiments & tools" ;;
      *)         desc="" ;;
    esac
    echo "" >> "$INDEX_FILE"
    echo "## $entry_root" >> "$INDEX_FILE"
    [[ -n "$desc" ]] && echo "_${desc}_" >> "$INDEX_FILE"
    echo "" >> "$INDEX_FILE"
    current_root="$entry_root"
  fi

  display_name=$(basename "$link_name")
  echo "### $display_name" >> "$INDEX_FILE"
  echo "" >> "$INDEX_FILE"

  while IFS= read -r md_file; do
    vault_rel="${md_file#$VAULT_DIR/}"
    file_display=$(basename "$md_file" .md)
    echo "- [[$vault_rel|$file_display]]" >> "$INDEX_FILE"
  done < <(find -L "$VAULT_DIR/$link_name" -name "*.md" -type f 2>/dev/null | sort)
  echo "" >> "$INDEX_FILE"
done

echo ""
echo "docs-hub-sync: done. ${#PROJECTS[@]} projects linked."
